enum GameActionTypes {
  UPDATE_FIELD_SIZE = 'UPDATE_FIELD_SIZE',
  RESET_SCORE = 'RESET_SCORE',
  OPEN_EMPTY_CELL = 'OPEN_EMPTY_CELL',
  ADD_POINTS_FOR_BOMBS = 'ADD_POINTS_FOR_BOMBS'
}

export default GameActionTypes;
